### ISSUE TITLE
Responses keeps repeating when replaced floating robot head with unity's standard assest character model(Ethan)

### ISSUE THREAD

**Issue by ck4957** [ActiveNick/HoloBot#4]
Hi,
I am trying to replace floating robot head with standard human character (ethan) and copied all the components from Drone to human character (ethan). It gets successfully deployed on hololens emulator but responses keeps repeating the same caption text when I gaze on the character and the ping audio source is not triggered for interaction.
Is there any changes needed to any script.? 
It works fine with drone face.

**Comment by ActiveNick** [comment]
I have not experimented with replacing the drone head with another model yet, but this is something I want to document since I expect many will want to do so. I am finally spending more time on this project. The project has been updated to Unity 5.6.2f1 and now uses the Direct Line 3.0 API. I am currently in the process of updating to the latest version of the HoloToolkit. Stay tuned for more info on how to update the model. More features to come too.

**Comment by ActiveNick** [comment]
I will close this for now since the entire speech support has been replaced with the Cognitive Services Speech SDK. if there are issues with the new implementation, please file a separate issue.
