### ISSUE TITLE
Avoid letting the bot repeat "http" when it speaks

### ISSUE THREAD

**Issue by andreapoppy** [ActiveNick/HoloBot#6]
This is not at all an issue, rather a simple idea. Instead of letting the bot repeat the http:// part of a url, try to skip it, as we people do when speaking about a particular url. This will make the bot sound more human in my opinion.

Keep doing a great job Nick.
Cheers

**Comment by ActiveNick** [comment]
I agree and it's on my to-do list. I'll add a module that "simplifies" spoken results that come back from the bot. I should be able to add that soon, stay tuned. Thanks.

**Comment by ActiveNick** [comment]
By the way, since HoloBot is a "speech aware" Bot Framework channel, it uses the Speak tag in the response. My recommendation to Bot Builders is to filter out such "http://" text on the bot side for the Speak tag, but leave it in for the displayed Text tag. This is what I have now done for The Maker Show bot which is used in the default HoloBot implementation. That said, I also plan on adding client-side text filtering like this to make HoloBot more universal when conversing to non-speech enabled bots.

**Comment by ActiveNick** [comment]
As mentioned above, I recommend that this be handled at the bot level, not in HoloBot. To see an example of this, check out the [BetterSpokenUrl function I included in TheMakerShowBot](https://github.com/ActiveNick/TheMakerShowBot/blob/3a48d0942ff511c5d1fdad964405abe31782ec6a/TheMakerShowBot/Dialogs/RootLuisDialog.cs#L45). Closing this issue for now.
