### ISSUE TITLE
Fails to compile on Unity 2017.1.0f3

### ISSUE THREAD

**Issue by NiteLordz** [ActiveNick/HoloBot#7]
File: CustomMaterialEditor.cs 
Error: No overload for method 'BeginAnimatedCheck' takes 1 argument

Method is looking for the first argument to be of type Rect().

Note: This file is part of HoloToolkit, so it might just need to be updated

**Comment by ActiveNick** [comment]
Thanks Stephen, that is why I have not updated HoloBot to 2017.1, I'm waiting for the updated release of HoloToolkit for that version of Unity. I prefer not to mess with HoloToolkit files in other projects otherwise it could break things down the line. I will leave this open until resolved. Stay tuned.

**Comment by NiteLordz** [comment]
Sounds good, I just wanted to make a note of it for ya

**Comment by ActiveNick** [comment]
Closing this issue now that HoloBot has been ported to 2017.2.
